# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Game Devs of Color Expo (July 10 + 11 in NYC)
email: gdocexpo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Game Devs of Color Expo is an inclusive games expo and conference creating a new normal in games by putting creators of color at the forefront, showing off their games, building conversations, and pushing games forward as an artform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gamedevsofcolorexpo.com" # the base hostname & protocol for your site
common_username:  GDoCE
company_info: >
  The 2020 Game Devs of Color Expo is produced by a diverse team of game creators and enthusiasts. We believe that games are for everyone and that the only path forward is to actively work to enable more games to be created by people of diverse backgrounds and get those games played by more people.

# Build settings
markdown: kramdown

# paricipate temporatily added to prevent users from finding the page via google, etc.
exclude: [participate]
