# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Game Devs of Color Expo (July 2019 in NYC)
email: gdocexpo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  GDoCExpo is an inclusive games expo and conference that features creators from across a spectrum of backgrounds showing off their games, building culture, and pushing games forward as an artform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gamedevsofcolorexpo.com" # the base hostname & protocol for your site
common_username:  GDoCE
company_info: >
  The GDoCE Organization Team is a team individuals of various backgrounds from across the country. We believe in using games as a means of social change as well as encouraging cultural change in the games industry.

# Build settings
markdown: kramdown

# paricipate temporatily added to prevent users from finding the page via google, etc.
exclude: [participate]
